# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpmJMyDN-tpGHmI6OxDOFI0cFuyKgKj2
"""

import streamlit as st
import pandas as pd
import joblib


# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Monitoreo de Estabilidad Hidráulica",
    page_icon="⚙️",
    layout="wide"
)


# ============================================================
# CARGA DEL MODELO
# ============================================================

@st.cache_resource
def cargar_modelo():
    return joblib.load("modelo_hidraulico_rf.pkl")


modelo = cargar_modelo()

pipeline = modelo["pipeline"]
features = modelo["features"]
defaults = modelo["defaults"]


# ============================================================
# ENCABEZADO
# ============================================================

st.title("Monitoreo de Estabilidad de un Sistema Hidráulico")

st.markdown(
    """
    Esta aplicación utiliza un modelo de **Random Forest** optimizado
    mediante validación cruzada para clasificar la condición del sistema
    hidráulico.

    **Clase 0:** Inestable
    **Clase 1:** Estable
    """
)

st.divider()


# ============================================================
# INFORMACIÓN DEL MODELO
# ============================================================

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Modelo", "Random Forest")

with col2:
    st.metric("Variables", len(features))

with col3:
    st.metric("SMOTE", "Sí")


st.divider()


# ============================================================
# ENTRADA DE VARIABLES
# ============================================================

st.subheader("Variables de entrada")

st.info(
    "Ingrese los valores estadísticos correspondientes al ciclo de "
    "operación que desea evaluar. Los campos se inicializan con la "
    "mediana observada en los datos de entrenamiento."
)


valores = {}

# Agrupar visualmente las variables por prefijo
grupos = {}

for feature in features:
    prefijo = feature.split("_")[0]

    if prefijo not in grupos:
        grupos[prefijo] = []

    grupos[prefijo].append(feature)


for grupo, variables in grupos.items():

    with st.expander(f"Variables {grupo}", expanded=True):

        columnas = st.columns(2)

        for i, feature in enumerate(variables):

            with columnas[i % 2]:

                valores[feature] = st.number_input(
                    feature,
                    value=float(defaults[feature]),
                    format="%.6f"
                )


# ============================================================
# PREDICCIÓN
# ============================================================

st.divider()

if st.button(
    "Predecir estabilidad",
    type="primary",
    use_container_width=True
):

    entrada = pd.DataFrame(
        [[valores[feature] for feature in features]],
        columns=features
    )

    prediccion = pipeline.predict(entrada)[0]

    probabilidades = pipeline.predict_proba(entrada)[0]

    prob_inestable = probabilidades[0]
    prob_estable = probabilidades[1]


    # --------------------------------------------------------
    # RESULTADO
    # --------------------------------------------------------

    st.subheader("Resultado de la predicción")

    if prediccion == 1:

        st.success(
            "El modelo clasifica el sistema como ESTABLE."
        )

    else:

        st.error(
            "El modelo clasifica el sistema como INESTABLE."
        )


    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            "Probabilidad de inestabilidad",
            f"{prob_inestable:.2%}"
        )

    with col2:
        st.metric(
            "Probabilidad de estabilidad",
            f"{prob_estable:.2%}"
        )


    st.progress(
        float(prob_estable),
        text=f"Probabilidad de estabilidad: {prob_estable:.2%}"
    )


# ============================================================
# INFORMACIÓN
# ============================================================

st.divider()

st.caption(
    "Proyecto Integrador - CRISP-DM | Despliegue de Modelo de "
    "Aprendizaje de Máquina"
)